server:
  port: 9093
  servlet:
    context-path: /file
    encoding:
      force-request: true
      force-response: true
spring:
  application:
    name: file
  profiles:
    active: @profile.active@
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: 100MB
  jackson:
    date-format: yyyy-MM-d HH:mm:ss
    time-zone: GMT+8
  redis:
    url: @redis.url@
    database: @redis.database@
  cloud:
    #nacos配置
    nacos:
      username: @nacos.userName@
      password: @nacos.passWord@
      discovery:
        server-addr: @nacos.address@
        service: ${spring.application.name}
        #配置了context-path时 必须配置如下代码将context-path加入Springboot Admin 监控地址
        metadata:
          management:
            context-path: ${server.servlet.context-path}/actuator
knife4j:
  enable: true
#配置暴露所有监控端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
#minio文件存储
minio:
  url: @minio.url@
  # 账号
  access-key: @minio.access-key@
  # 密码
  secret-key: @minio.secret-key@
  #桶名称
  bucket-name: @minio.bucket-name@
#fastdfs文件存储
fdfs:
  domain: http://fvdfvd
