spring:
  datasource:
    druid:
      url: jdbc:mysql://101.37.117.70:3306/xxl-job?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&serverTimezone=Asia/Shanghai
      username: root
      password: eb29fbfc4d46d9e5