server:
  port: 9000
spring:
  application:
    name: gateway
  profiles:
    active: @profile.active@
  cloud:
    nacos:
      discovery:
        server-addr: @nacos.address@
        service: ${spring.application.name}
        username: @nacos.userName@
        password: @nacos.passWord@
    gateway:
      enabled: true
      #Global timeouts
      #      httpclient:
      #the default is 45s
      #        connect-timeout: 10000
      #        response-timeout: 10s
      routes:
        #system路由配置
        - id: system
          uri: lb://system
          predicates:
            - Path=/api/system/**
          filters:
            - StripPrefix=1
        #account路由配置
        - id: account
          uri: lb://account
          predicates:
            - Path=/api/account/**
          filters:
            - StripPrefix=1
        #business路由配置
        - id: business
          uri: lb://business
          predicates:
            - Path=/api/business/**
          filters:
            - StripPrefix=1
        #order路由配置
        - id: order
          uri: lb://order
          predicates:
            - Path=/api/order/**
          filters:
            - StripPrefix=1
        #storage路由配置
        - id: storage
          uri: lb://storage
          predicates:
            - Path=/api/storage/**
          filters:
            - StripPrefix=1
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-d HH:mm:ss
