server:
  port: 9091
spring:
  application:
    name: gateway
  profiles:
    active: @profile.active@
  cloud:
    nacos:
      username: @nacos.userName@
      password: @nacos.passWord@
      discovery:
        server-addr: @nacos.address@
        service: ${spring.application.name}
    gateway:
      enabled: true
      #Global timeouts
      #      httpclient:
      #the default is 45s
      #        connect-timeout: 10000
      #        response-timeout: 10s
      routes:
        #system路由配置
        - id: system
          uri: lb://system
          predicates:
            - Path=/api/system/**
          filters:
            - StripPrefix=1
        #file路由配置
        - id: file
          uri: lb://file
          predicates:
            - Path=/api/file/**
          filters:
            - StripPrefix=1
        #gen路由配置
        - id: gen
          uri: lb://gen
          predicates:
            - Path=/api/gen/**
          filters:
            - StripPrefix=1
        #app路由配置
        - id: app
          uri: lb://app
          predicates:
            - Path=/api/app/**
          filters:
            - StripPrefix=1
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-d HH:mm:ss
  #redis配置
  redis:
    url: @redis.url@
    database: @redis.database@
#配置暴露所有监控端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
