server:
  port: 9096
  servlet:
    context-path: /app
    encoding:
      force-request: true
      force-response: true
  # 当request header中存在 Accept-Encoding时 对response压缩
  compression:
    enabled: true
spring:
  application:
    name: app
  profiles:
    active: @profile.active@
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: 100MB
  #数据库连接池配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      #配置初始化大小、最小、最大
      initial-size: 5
      min-idle: 10
      max-active: 20
      #配置获取连接等待超时的时间
      max-wait: 6000
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 20000
      #配置一个连接在池中最小、最大生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 600000
      max-evictable-idle-time-millis: 900000
      validation-query: "select 1"
      test-while-idle: false
      test-on-borrow: false
      test-on-return: false
      keep-alive: true
      async-init: true
      #fliters
      filters: stat,slf4j
      #配置日志输出
      filter:
        slf4j:
          enabled: true
          statement-create-after-log-enabled: false
          statement-close-after-log-enabled: false
          result-set-open-after-log-enabled: false
          result-set-close-after-log-enabled: false
          #是否显示SQL语句
          statement-executable-sql-log-enable: true
          #是否显示预处理sql
          statement-prepare-after-log-enabled: false
          #是否显示执行语句
          statement-execute-after-log-enabled: false
        stat:
          log-slow-sql: true
          slow-sql-millis: 3000
  jackson:
    date-format: yyyy-MM-d HH:mm:ss
    time-zone: GMT+8
  #redis配置
  redis:
    url: @redis.url@
    database: @redis.database@
  cloud:
    #nacos配置
    nacos:
      discovery:
        server-addr: @nacos.address@
        service: ${spring.application.name}
        #配置了context-path时 必须配置如下代码将context-path加入Springboot Admin 监控地址
        metadata:
          management:
            context-path: ${server.servlet.context-path}/actuator
      username: @nacos.userName@
      password: @nacos.passWord@
pagehelper:
  params: pageNum=pageNum;pageSize=pageSize;count=countSql;
  #支持通过 Mapper 接口参数来传递分页参数，默认值false，分页插件会从查询方法的参数值中，自动根据上面 params 配置的字段中取值
  support-methods-arguments: true
  #分页合理化参数，默认值为false。当该参数设置为 true 时，pageNum<=0 时会查询第一页，
  #pageNum>pages（超过总数时），会查询最后一页。默认false 时，直接根据参数进行查询。
  reasonable: true
  #默认值为 false，当该参数设置为 true 时，如果 pageSize=0 或者 RowBounds.limit = 0 就会查询出全部的结果
  #（相当于没有执行分页查询，但是返回结果仍然是 Page 类型）。
  page-size-zero: true
mybatis-plus:
  mapper-locations: classpath*:mybatis/*.xml
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: assign_id
knife4j:
  enable: true
#Seata client端 nacos 配置
seata:
  enabled: true
  application-id: ${spring.application.name}
  #事务分组名称 若不配置，默认获取属性spring.application.name的值+"-fescar-service-group"
  tx-service-group: ${spring.application.name}_group
  enable-auto-data-source-proxy: true
  data-source-proxy-mode: AT
  use-jdk-proxy: false
  service:
    vgroup-mapping:
      app_group: default
  registry:
    type: nacos
    load-balance: RandomLoadBalance
    load-balance-virtual-nodes: 10
    nacos:
      namespace: ""
      server-addr: @nacos.address@
      group: "SEATA_GROUP"
      username: @nacos.userName@
      password: @nacos.passWord@
      #与 seata server 配置的application一致
      application: seata-server
# 暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always