server:
  port: 8082
spring:
  application:
    name: job-executor
  profiles:
    active: @profile.active@
  cloud:
    nacos:
      discovery:
        server-addr: @nacos.address@
        username: @nacos.userName@
        password: @nacos.passWord@
#配置暴露所有监控端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always