spring:
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/business?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&serverTimezone=Asia/Shanghai
      username: cloud-vue
      password: cloud-vue
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
#    password: zhuweiwei