server:
  port: 9094
  servlet:
    context-path: /monitor
spring:
  application:
    name: monitor
  profiles:
    active: @profile.active@
  security:
    user:
      name: @monitor.login.username@
      password: @monitor.login.password@
  boot:
    admin:
      ui:
        title: @monitor.login.title@
  cloud:
    #nacos配置
    nacos:
      username: @nacos.userName@
      password: @nacos.passWord@
      discovery:
        server-addr: @nacos.address@
        service: ${spring.application.name}
        #配置了context-path时 必须配置如下代码将context-path加入Springboot Admin 监控地址
        metadata:
          management:
            context-path: ${server.servlet.context-path}/actuator
#配置暴露所有监控端点 http://localhost:9094/monitor/actuator
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always